TestRunner.cs
src/Assertions.cs
src/ISceneRunner.cs
src/asserts/ExceptionAssert.cs
src/core/GdUnitConsole.cs
src/core/SceneRunner.cs
src/core/execution/ExecutionContext.cs
src/core/exensions/GodotObjectExtension.cs
test/core/SceneRunnerTest.cs
test/core/resources/scenes/Spell.gd
test/core/resources/scenes/TestScene.gd

the test is broken at differnt scenarios and needs to be fixed
- Fix `GetProperty` to handle null values
- Add missing `SetProperty`
- Add `SyncProcessFrame` and `SyncPhysicsFrame` to join the Godot process
- Fix broken `AwaitSignal`
- Fix `GodotMethodAwaiter` to wait a function call is finished
- Add missing `FindChild`
- Extend `ExceptionAssert` to handle method calls with no return values
- better console outputt
- Fix Execution context to handle already disposed objects

GD-9: Fix SceneRunnerTest

---

api/gdUnit4MonoApi.csproj
api/src/Assertions.cs
api/src/CsNode.cs
api/src/GdUnit4MonoAPI.cs
api/src/IExecutor.cs
api/src/core/GdUnitTestSuiteBuilder.cs
api/src/core/attributes/TestCaseAttributes.cs
api/src/core/execution/ExecutionContext.cs
api/src/core/execution/Executor.cs
api/src/core/execution/TestSuiteExecutionStage.cs
api/src/core/exensions/GdUnitExtensions.cs
gdUnit4Mono.csproj
test/gdUnit4MonoTest.csproj
test/src/AssertionsTest.cs
test/src/api/TestRunner.cs
test/src/asserts/EnumerableAssertTest.cs
test/src/core/ExecutorTest.cs
test/src/core/GdUnitTestSuiteBuilderTest.cs

- update to Godot.NET.Sdk/4.1.2
- fixed warnings
- fixed parameterized test naming

Prepare GdUnit4Mono 4.2.0.0 release candidate

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/actions/godot-install/action.yml
.github/actions/publish-test-report/action.yml
.github/actions/unit-test/action.yml
.github/actions/upload-test-report/action.yml
.github/actions/workflow-cleanup/index.js
.github/workflows/ci-pr.yml
.github/workflows/unit-tests.yml
.github/workflows/workflow-cleanup.yml
test/nuget.config
test/project.godot

We need an automated way to run all tests on a pull request.
Enable CI for pull requests.
- install godot
- build the project
- run tests via provides test runner

GD-11: Add continue integration tests for pull request

---

api/gdUnit4Api.csproj
example/exampleProject.csproj
global.json
test/gdUnit4Test.csproj
testadapter/README.md
testadapter/gdUnit4TestAdapter.csproj

I had only net8 installed, so I had to make some changes to allow both net7 and net8

Support both net7 and net8 at once

---

.editorconfig
PackageVersions.props
api/src/asserts/StringAssert.cs
api/src/core/GdUnitTestSuiteBuilder.cs
api/src/core/SceneRunner.cs
api/src/core/execution/AfterExecutionStage.cs
api/src/core/execution/AfterTestExecutionStage.cs
api/src/core/execution/Executor.cs
api/src/core/execution/TestCase.cs
api/src/core/execution/TestFailedException.cs
api/src/core/execution/TestSuite.cs
api/src/core/execution/TestSuiteExecutionStage.cs
api/src/core/exensions/GdUnitExtensions.cs
api/src/core/exensions/GodotVariantExtensions.cs
example/exampleProject.csproj
global.json
test/.runsettings
test/gdUnit4Test.csproj
testadapter/src/GdUnit4TestDiscoverer.cs
testadapter/src/GdUnit4TestExecutor.cs
testadapter/src/execution/ITestExecutor.cs
testadapter/src/execution/TestExecutor.cs

We want to support the latest .NET version
- switch to SDK 8.0.0
- update runsettings to support .NET7 and .NET8
- use for test and example project .NET8

GD-62: Add full .NET8 support

---

api/src/IExceptionAssert.cs
api/src/ISceneRunner.cs
api/src/asserts/ExceptionAssert.cs
api/src/core/SceneRunner.cs
api/src/core/execution/ExecutionStage.cs
api/src/core/exensions/GodotObjectExtension.cs
api/src/core/exensions/GodotVariantExtensions.cs
clean.sh
test/project.godot
test/src/asserts/AssertionsTest.cs
test/src/core/SceneRunnerCSharpSceneTest.cs
test/src/core/SceneRunnerGDScriptSceneTest.cs
test/src/core/TestSuiteFailWithExceptions.cs
test/src/core/resources/scenes/TestSceneWithExceptionTest.cs
test/src/core/resources/scenes/TestSceneWithExceptionTest.tscn

When using `Invoke` on the `SceneRunner`, no exceptions are forwarded because Godot `call` does not transfer the exceptions to C# scripts.
- Refactor the `Invoke` extension do handle it explicitly for `GDScripts` and `CSharpScripts`.
- Fix handle calling static methods when invoke
- `SceneRunner::Invoke` forward to  `Invoke` extension implementation
- Added new `InvokeAsync` to the `SceneRunner` to support async calls
- Fix invalid Variant unboxing of integer and float
- Improved the `ExceptionAssert` by providing new methods to verify for exception file line number and file name

GD-22: Calling Invoke on `SceneRunner` must propagate exceptions

---

api/src/IExceptionAssert.cs
api/src/asserts/AssertBase.cs
api/src/asserts/ExceptionAssert.cs
api/src/asserts/ObjectAssert.cs
api/src/core/execution/ExecutionStage.cs
api/src/core/execution/TestFailedException.cs
api/src/core/report/TestReport.cs
test/src/asserts/AssertionsTest.cs
test/src/asserts/BoolAssertTest.cs
test/src/asserts/DictionaryAssertTest.cs
test/src/asserts/EnumerableAssertTest.cs
test/src/asserts/ExceptionAssertTest.cs
test/src/asserts/NumberAssertTest.cs
test/src/asserts/ObjectAssertTest.cs
test/src/asserts/StringAssertTest.cs
test/src/asserts/VectorAssertTest.cs
testadapter/src/execution/BaseTestExecutor.cs

The stack trace was not complete and misses test execution frames.
- Complete rework on `TestFailedException` to provide now the stack trace.
- Fix some issued detected during refactoring on `ExceptionAssert`
- The `TestReport` do now submit the stack trace and is read on test adapter to fill the `ErrorStackTrace`

GD-49: Revision of the stack trace collection for failed tests

---

.vscode/extensions.json
api/src/Assertions.cs
api/src/IDictionyryAssert.cs
api/src/asserts/AssertBase.cs
api/src/asserts/AssertFailures.cs
api/src/asserts/BoolAssert.cs
api/src/asserts/DictionaryAssert.cs
api/src/asserts/EnumerableAssert.cs
api/src/asserts/ExceptionAssert.cs
api/src/asserts/VectorAssert.cs
api/src/core/execution/ExecutionStage.cs
api/src/core/exensions/GdUnitExtensions.cs
api/src/core/exensions/GodotVariantExtensions.cs
test/src/asserts/AssertionsTest.cs
test/src/asserts/DictionaryAssertTest.cs
test/src/asserts/ObjectAssertTest.cs
test/src/asserts/SignalAssertTest.cs

The API differs between `GDScript` and C# and needs to be reconciled.
- Fix Generic type namings
- Fix formatting issues on `AssertFailures` to handle Godot generic types and improve object instance rendering
- Fix invalid stack trace for unexpected exceptions
- `IDictionaryAssert` completely revised
- fixes issues to handle generic dictionaries
- ContainsSameKeyValue ✅
- ContainsSameKeys ✅
- NotContainsSameKeys ✅
- IsNotSame ✅
- IsSame ✅

GD-10: Complete missing features for `IDictionaryAssert`

---

api/src/Assertions.cs
api/src/IDictionyryAssert.cs
api/src/IEnumerableAssert.cs
api/src/asserts/AssertBase.cs
api/src/asserts/AssertFailures.cs
api/src/asserts/DictionaryAssert.cs
api/src/asserts/EnumerableAssert.cs
api/src/core/execution/TestCase.cs
api/src/core/execution/TestSuite.cs
api/src/core/exensions/GdUnitExtensions.cs
api/src/core/exensions/GodotVariantExtensions.cs
api/src/extractors/Tuple.cs
test/src/asserts/AssertionsTest.cs
test/src/asserts/EnumerableAssertTest.cs
test/src/asserts/SignalAssertTest.cs
test/src/core/ExecutorTest.cs
testadapter/src/GdUnit4TestDiscoverer.cs

The API differs between GDScript and C# and needs to be reconciled.
- improve messages on `AssertFailures` to accept generic types
- fix formatting issues for `IEnumerables`
- fix test case name building by using `TestCase.BuildTestCaseName` discovered after fixing the `IEnumerables` formattings
- rebuild `IEnumerableAssert` to make it generic
- ContainsSame ✅
- ContainsSameExactly ✅
- ContainsSameExactlyInAnyOrder ✅
- IsNotSame ✅
- IsSame ✅
- NotContains ✅
- NotContainsSame ✅

GD-10: Complete missing features for `IEnumerableAssert`

---

api/src/INumberAssert.cs
api/src/asserts/AssertFailures.cs
api/src/asserts/NumberAssert.cs
api/src/core/execution/TestCase.cs
api/src/core/exensions/GdUnitExtensions.cs
test/src/asserts/NumberAssertTest.cs

We missed the `IsEqualApprox` on `INumberAssert` and need to be implemented.
- Sharpening the `INumberAssert` TValue type by add number specific interface requirements
- Fix decimal value formattings to handle it centralized at `GdUnitExtensions`

GD-10: Complete missing features for `INumberAssert`

---

.github/workflows/ci-pr.yml
api/gdUnit4Api.csproj
api/src/ISceneRunner.cs
api/src/core/SceneRunner.cs
example/exampleProject.csproj
test/src/core/SceneRunnerInputEventIntegrationTest.cs
testadapter/gdUnit4TestAdapter.csproj

With https://github.com/MikeSchulze/gdUnit4/pull/329 we changed the method signature of `SimulateMouseMoveRelative` and introduced `SimulateMouseMoveAbsolute`
- Implement the `SimulateMouseMoveRelative` and `SimulateMouseMoveAbsolute`
- set API version 4.2.2-rc.1
- fix NuGet package dependencies resolving to include pre releases

GD-32: Add missing `SimulateMouseMoveRelative` and `SimulateMouseMoveAbsolute` to `ISceneRunner `

---

api/src/core/GdUnitTestSuiteBuilder.cs
api/src/core/execution/ExecutionContext.cs
api/src/core/execution/TestCase.cs
api/src/core/execution/TestSuite.cs
example/.runsettings
example/.runsettings-ci
test/.runsettings
test/.runsettings-ci
test/src/core/ExampleTestSuite.cs
test/src/core/GdUnitTestSuiteBuilderTest.cs
testadapter/src/GdUnit4TestDiscoverer.cs
testadapter/src/execution/BaseTestExecutor.cs

The property `DisplayName` allows configuring between `SimpleName` and `FullyQualifiedName` but it runs into issues where the tests were not discovered or executed.
- fixes the building of `DisplayName`:
- do provide the full test name inclusive parameters when  `FullyQualifiedName`  is set
- do provide the short test name exclusive parameters, but with index when  `SimpleName`  is set
- fix test filter to work on full qualified names
- simplify discover tests and fix the display name building
- fix custom name handling for single test cases (it was ignored)
- switch back to `FullyQualifiedName` on all `.runsettings`

GD-76: Fix `DisplayName` resolving on test adapter

---

.github/workflows/unit-tests.yml
api/gdUnit4Api.csproj
api/src/Assertions.cs
api/src/asserts/AssertBase.cs
api/src/asserts/DictionaryAssert.cs
api/src/asserts/EnumerableAssert.cs
api/src/asserts/ObjectAssert.cs
example/exampleProject.csproj
example/test/api/AssertionsTest.cs
test/gdUnit4Test.csproj

https://github.com/MikeSchulze/gdUnit4Net/issues/84 The dynamic resolving was broken because the using assembly has no access to assert types that were marked as internally.
Fixes by make the asserts used by the dynamic resolving public. Do a small cleanup on the dynamic assert resolving

GD-84: Fix `AssertThat` for dynamic assert type resolving

---

PackageVersions.props
api/gdUnit4Api.csproj
example/exampleProject.csproj
testadapter/gdUnit4TestAdapter.csproj
testadapter/src/execution/TestExecutor.cs

https://github.com/MikeSchulze/gdUnit4Net/issues/86
* fixed the arguments that include paths by surrounding by quotes.
* set working directory to project path
* use current working directory to set the `--path .` argument
* introduce package version properties to centralize the API versions
* bump adapter version to v1.1.1

GD-86: Fixes space in folder name prevents tests from running

---

.github/ISSUE_TEMPLATE/bug_gdunit4_api.yaml
.github/ISSUE_TEMPLATE/bug_gdunit4_test_adapter.yaml
.github/workflows/ci-pr.yml
.vscode/settings.json
PackageVersions.props
api/ReleaseNotes.txt
api/src/ISceneRunner.cs
api/src/core/SceneRunner.cs
test/src/core/SceneRunnerInputEventIntegrationTest.cs

We want to simulate input actions on a running scene.
added new simulate methods to the SceneRunner
```cs
/// <summary>
/// Simulates that an action has been pressed.
/// </summary>
/// <param name="action">The name of the action, e.g., "ui_up".</param>
/// <returns>The SceneRunner instance.</returns>
ISceneRunner SimulateActionPressed(string action);
/// <summary>
/// Simulates that an action is press.
/// </summary>
/// <param name="action">The name of the action, e.g., "ui_up".</param>
/// <returns>The SceneRunner instance.</returns>
ISceneRunner SimulateActionPress(string action);
/// <summary>
/// Simulates that an action has been released.
/// </summary>
/// <param name="action">The name of the action, e.g., "ui_up".</param>
/// <returns>The SceneRunner instance.</returns> …
```

GD-89: Add input action support to the `SceneRunner`

---

.gitignore
testadapter/src/execution/BaseTestExecutor.cs

On Visual Studio, there are leftovers when press stop debug on a test session. This results into a `The active test run was aborted. Reason: Test host process crashed` This crash can't be handled by the test executor because the process is lost.
- added to `.gitignore` a rule do not push runner config files
- do delete now old runner config files if exist before write the new one. This is just a workaround to clean up the working directory

GD-90: Cleanup old runner configuration before run new tests

---

PackageVersions.props
api/src/asserts/AssertFailures.cs
test/src/asserts/AssertionsTest.cs

see https://github.com/MikeSchulze/gdUnit4Net/issues/94
Now consider `ToString()` to create the error message.

GD-94: Improve assertions error message when comparing objects

---

PackageVersions.props
api/src/core/execution/TestCase.cs
api/src/core/execution/TestSuiteExecutionStage.cs
test/src/core/ExampleTestSuite.cs
test/src/core/ExecutorTest.cs
test/src/core/GdUnitTestSuiteBuilderTest.cs
test/src/core/resources/testsuites/mono/TestSuiteParameterizedTests.cs

https://github.com/MikeSchulze/gdUnit4Net/issues/96
There was a wrong check to switch between single and parameterized tests. Added a more intuitive test case parameter to verify if a test is parameterized

GD-96: Fix methods with a single parameterized test case are not executed

---

api/src/core/GdUnit4Settings.cs
api/src/core/execution/Executor.cs
test/src/core/ExecutorTest.cs

https://github.com/MikeSchulze/gdUnit4Net/issues/101
- added GdUnit4Settings to access the gdunit4 properties
- use `IsVerboseOrphans` to determine report orphans is enabled
- fix executor test to use the property instead of hard coded value

GD-101: Respect the GdUnit4 settings to notify about orphan nodes

---

PackageVersions.props
api/src/core/execution/ExecutionStage.cs
test/gdUnit4Test.csproj
test/src/asserts/AssertionsTest.cs

https://github.com/MikeSchulze/gdUnit4Net/issues/103
- do filter all stack frames out containing `Microsoft.VisualStudio.TestTools`
changes to:

GD-103: Trim MSTest assert stack trace

---

api/src/core/execution/ExecutionStage.cs
api/src/core/execution/TestSuiteExecutionStage.cs
test/.runsettings
test/src/core/ExecutorTest.cs
test/src/core/resources/testsuites/mono/TestSuiteAllTestsFailWithExceptions.cs

see https://github.com/MikeSchulze/gdUnit4Net/issues/106
fixing the extraction of inner exception to catch the right exception message

GD-104: Fix exception failure message propagation

---

api/src/ISceneRunner.cs
api/src/core/SceneRunner.cs
test/gdUnit4Test.csproj
test/src/core/SceneRunnerCSharpSceneTest.cs
test/src/core/resources/scenes/TestSceneWithInitialization.cs
test/src/core/resources/scenes/TestSceneWithInitialization.tscn

[GD-110](https://github.com/MikeSchulze/gdUnit4Net/issues/110)
- Added overloaded ISceneRunner.Load that accepts a Node
- Pulled scene loading logic out of the SceneRunner constructor and into the ISceneRunner.Load method
Tests can now initialize or use the root node of a scene before it is loaded and any _Ready functions are called on it.
Ex.
```
public partial class MyNode : Node2d
{ 
public void Initialize(int foo) { ... }
}
[TestSuite]
public class MyNodeTest  
{ 
[TestCase]
public void  MyNodeInitTest()
{
var myNode = new MyNode();
myNode.Initialize(12);
var sceneRunner = ISceneRunner.Load(myNode);
...
}
}
```

GD-110: Allow a Node to be passed in to SceneRunner.Load as the root of the scene.

---

testadapter/src/utilities/Utils.cs

The test adapter shows the wrong version in the output logs, the statically bound version was used.
- We now load the assembly and extract the version

GD-114: Fix test adapter `gdUnit4.api` version resolving

---

.github/actions/upload-test-report/action.yml
.github/workflows/ci-pr-publish-report.yml
.github/workflows/unit-tests.yml
.gitignore
test/.runsettings
test/.runsettings-ci

See https://github.com/MikeSchulze/gdUnit4Net/issues/116
- removed the publish steps from the unit test WF and do only upload the test artifacts
- add seperate WF to download the test artifacts and publish it afterwards

GD-116:  Add publish WF to publish test reports in a separate way

---

api/src/Assertions.cs
api/src/ISignalAssert.cs
api/src/asserts/SignalAssert.cs
api/src/core/signals/GodotSignalCollector.cs
test/src/asserts/SignalAssertTest.cs

GD-121: Add signal monitor
The emitted signals needs to be monitored over the test runtime.
Provides a new method for starting signal monitoring.
It should be called up directly after the emitter has been created in order to start monitoring the emitted signals.

GD-121: Improve `AssertSignal` by adding a `StartMonitoring` method

---

.github/workflows/ci-pr-publish-report.yml
.github/workflows/ci-pr.yml
example/exampleProject.csproj
global.json
test/gdUnit4Test.csproj
test/src/core/SceneRunnerInputEventIntegrationTest.cs

We get an compile warning using Godot less than 4.3.beta1  `Godot.SourceGenerators.MustBeVariantAnalyzer` and had a temporary solution to filter them out `<NoWarn>$(NoWarn);AD0001</NoWarn>`
- Upgrade the dependencies to Godot.NET.Sdk `4.3.beta1` and remove the temporary hack
- Fixed failing input action tests according to the Godot 4.3 event changes

GD-87: Remove temporary solution of `Godot.SourceGenerators.MustBeVariantAnalyzer` warnings

---

api/ReleaseNotes.txt
api/src/ISceneRunner.cs
test/src/core/SceneRunnerCSharpSceneTest.cs
test/src/core/SceneRunnerGDScriptSceneTest.cs

see https://github.com/MikeSchulze/gdUnit4Net/issues/144
Added `AwaitInputProcessed` to `ISceneRunner` and fix scene runner integration tests

GD-144: Add AwaitInputProcessed to SceneRunner

---

.github/workflows/unit-tests.yml
PackageVersions.props
api/ReleaseNotes.txt
api/src/core/attributes/DataPointAttribute.cs
api/src/core/attributes/ThrowsExceptionAttribute.cs
api/src/core/data/AsyncDataPointCanceledException.cs
api/src/core/data/DataPointValueProvider.cs
api/src/core/execution/ExecutionContext.cs
api/src/core/execution/ExecutionStage.cs
api/src/core/execution/TestCase.cs
api/src/core/execution/TestSuiteExecutionStage.cs
example/exampleProject.csproj
example/test/ExampleTest.cs
test/src/core/ExternalDataPoints.cs
test/src/core/TestSuiteWithDynamicDataPoints.cs
test/src/core/TestSuiteWithExpectedExceptions.cs

https://github.com/MikeSchulze/gdUnit4Net/issues/46
added  `DataPointAttribute` to full support RFC 006 - DynamicData
```cs
public static IEnumerable<object[]> ArrayDataPointProperty => new[] { new object[] { 1, 2, 3 }, new object[] { 4, 5, 9 } };
[TestCase]
[DataPoint(nameof(ArrayDataPointProperty))]
public void OnArrayDataPointProperty(int a, int b, int expected) => AssertThat(a + b).IsEqual(expected);
```
```cs
public static IEnumerable<int> SingleDataPointProperty => new[] { 1, 2, 3 };
[TestCase]
[DataPoint(nameof(SingleDataPointProperty))]
public void OnSingleDataPointProperty(int value) => AssertThat(value).IsBetween(1, 3);
```
```cs
public static IEnumerable<object[]> ArrayDataPointMethod() => new[] { new object[] { 1, 2, 3 }, new object[] { 4, 5, 9 } };
[TestCase] …
```

GD-46: Added support of DataPoint attributes, which make it possible to define parameterized tests with dynamic test data

---

.github/actions/upload-test-report/action.yml
.github/workflows/unit-tests.yml
testadapter.test/gdUnit4TestAdapter.Tests.csproj
testadapter.test/test/TestUtils.cs
testadapter.test/test/resources/project.godot
testadapter.test/test/resources/project.godot2
testadapter.test/test/settings/GodotProjectSettingsTest.cs
testadapter.test/test/settings/RunSettingsProviderTest.cs
testadapter.test/test/utilities/UtilsTest.cs
testadapter/src/execution/TestExecutor.cs
testadapter/src/settings/GodotProjectSettings.cs
testadapter/src/utilities/Utils.cs

see https://github.com/MikeSchulze/gdUnit4Net/issues/163
- Added `GodotProjectSettings` to load the current project settings
- Copy finally the Godot log file into the results directory

GD-163: Collect the Godot log file into test report

---

analyzers.test/src/ExampleTest.cs
api/src/api/ITestEvent.cs
api/src/core/execution/ExecutionContext.cs
api/src/core/execution/TestEvent.cs
api/src/core/execution/TestSuiteExecutionStage.cs
test/src/core/ExampleTestSuite.cs
test/src/core/GdUnitTestSuiteBuilderTest.cs
testadapter/src/execution/TestEventReportListener.cs

The display name for tests using DataPoint attribute is misleading and not presents the name + test values
Added the optional display name, set only by data driven tests. The display name will be applied on test record if is set.

GD-152: Part5: Fix test case display name for dynamic test data driven tests

---

.github/workflows/unit-tests.yml
PackageVersions.props
api/src/core/runners/GdUnit4TestRunnerSceneCore.cs
api/src/core/runners/GdUnit4TestRunnerSceneTemplate.cs
api/src/core/runners/GodotRuntimeTestRunner.cs
example/exampleProject.csproj
example/nuget.config
example/test/api/AssertionsTest.cs

The installed test runner had no access to private classes like `GodotGdUnit4RestServer` and the run fails with an exception.
- Simplified the test runner to inherit from the test runner core where has internal access to avoid such errors
- set api to rc8
- update example project and fix test failure marked by the analyzer

GD-152: Part8: Fix test runner installation

---

PackageVersions.props
api/src/core/execution/ExecutionContext.cs
api/src/core/execution/ExecutionStage.cs
api/src/core/execution/TestSuiteExecutionStage.cs
api/src/core/execution/monitoring/GodotExceptionMonitor.cs
test/.editorconfig
test/src/core/execution/monitoring/ExampleEventBus.cs
test/src/core/execution/monitoring/ExampleWithWithEventBus.cs
test/src/core/execution/monitoring/GodotExceptionMonitorOnClassLevelTest.cs
test/src/core/execution/monitoring/GodotExceptionMonitorTest.cs

Exceptions thrown by an emitted signal was not cougthed. Using `GodotExceptionMonitor` at class level was ignored to enable the monitoring.
- Added `InvokeGodotClassMethod` on `IsSceneProcessingMethod` to detect Godot method calls
- Evaluate the class attribute `GodotExceptionMonitor` to enable the exception monitoring
- Fixes an issue on validate an expected exception by using the correct execution context method info

Fixes Godot exception monitoring issues

---

PackageVersions.props
api/src/api/TestEngineSettings.cs
api/src/core/runners/GodotRuntimeTestRunner.cs
test/.runsettings
test/src/core/runners/GodotRuntimeTestRunnerTest.cs
testadapter/src/GdUnit4TestExecutor.cs
testadapter/src/settings/GdUnit4Settings.cs

Improved the GodotRuntimeTestRunner to better handle different compilation scenarios and provide more robust error handling with proper resource cleanup.
- Updated ExitHandler to log errors with appropriate error level
- Added proper cleanup of runner files when compilation fails
- Ensured processes are properly terminated after timeout
- Added configurable CompileProcessTimeout setting
- Improved error messaging with detailed instructions for timeout cases

GD-199: TestRunner install ends with abnormal exit on large projects

---

LICENSE
README.md
analyzers/README.md
api/README.md
api/src/core/attributes/TestCategoryAttribute.cs
api/src/core/attributes/TraitAttribute.cs
api/src/core/discovery/TestCaseDescriptor.cs
api/src/core/discovery/TestCaseDiscoverer.cs
example/exampleProject.csproj
test/gdUnit4Test.csproj
test/src/core/ExampleTestSuite.cs
test/src/core/discovery/TestCaseDescriptorTest.cs
test/src/core/discovery/TestCaseDiscovererTest.cs
testadapter.test/test/NoOpLogger.cs
testadapter.test/test/execution/TestCaseFilterTest.cs
testadapter/README.md
testadapter/TestFilterGuide.md
testadapter/src/GdUnit4TestDiscoverer.cs
testadapter/src/GdUnit4TestExecutor.cs
testadapter/src/execution/TestCaseFilter.cs
testadapter/src/extensions/TestCaseExtensions.cs

We want to support the VSTest filter framework to allow users to selectively run tests based on various criteria, improving test workflow efficiency.
- Implement test filtering for VSTest integration
- Add TestCategoryAttribute for grouping related tests
- Add TraitAttribute for custom metadata and flexible filtering
- Create comprehensive TestFilterGuide.md documentation
- Update all README files with filter information and cross-references
- Add example filter syntax and usage patterns in documentation
This enables users to run specific tests using criteria like name, class, namespace, category, and custom traits across Visual Studio, VS Code, and JetBrains Rider.

GD-27: Add VSTest filter support with test categories and traits

---

Api.Test/src/asserts/VectorAssertTest.cs
Api/src/Assertions.cs
Api/src/asserts/VectorAssert.cs
Api/src/core/extensions/GodotVectorExtension.cs
Api/src/core/extensions/SystemVectorExtension.cs

Vector `IsEqualApprox` returns true even though vectors are not approximately equal
Reimplement `IsEqualApprox` and add more test coverage.

GD-212: Fix vector assertion `IsEqualApprox`

---

.github/workflows/unit-tests.yml
Api/GdUnit4Api.csproj
Api/build/gdUnit4.api.props
Api/buildTransitive/gdUnit4.api.props
Example/ExampleProject.csproj
Example/test/ExampleTest.cs
PackageVersions.props
TestAdapter.Test/test/discovery/GdUnit4TestDiscovererTest.cs

Add automatic conditional compilation support to enable optional GdUnit4 API usage in projects through the GDUNIT4NET_API_V5 constant.
- Add Compilation Constant `GDUNIT4NET_API_V5`

GD-240: Add `GDUNIT4NET_API_V5` Conditional Compilation Constant

---

.editorconfig
.github/workflows/unit-tests.yml
Analyzers.Test/src/VerifyDocumentationTest.cs
Analyzers.Test/test.ruleset
Analyzers/src/DataPointAttributeAnalyzer.cs
Analyzers/src/GodotRuntimeRequireAnalyzer.cs
Api/src/api/ITestEngineLogger.cs
Api/src/core/data/DataPointValueProvider.cs
Api/src/core/execution/ExecutionContext.cs
Directory.Packages.props
ProjectVersions.props
TestAdapter.Test/test.ruleset
TestAdapter.Test/test/execution/TestCaseFilterTest.cs
global.json
stylecop.ruleset

- Remove .NET 7 support
- Add .NET 9 support
- Set LangVersion to 12.0
- Temporarily disable C# 12 style warnings (IDE0028, IDE0290, IDE0300-IDE0306. ..)
Why:
- .NET 7 is going out of support
- .NET 8 is the current LTS version
- C# 12 is required for .NET 9 source generator compatibility
- Style warnings suppressed to maintain existing code patterns during transition

Upgrade to .NET 8/9 with C# 12 support

---

Api.Test/src/core/SceneRunnerCSharpSceneTest.cs
Api/src/Assertions.cs
Api/src/ISceneRunner.cs
Api/src/core/SceneRunner.cs

The  `AwaitSignalOn` is missing in the API and needs to be implemented.
- Add  `AwaitSignalOn` to ISceneRunner
- Add global  `AwaitSignalOn` method redirecting to ISceneRunner implementaion

GD-211: Implement missing `AwaitSignalOn`

---

Api/src/core/execution/GdUnit4RuntimeExecutorGodotBridge.cs
Api/src/core/extensions/GodotObjectExtensions.cs
ProjectVersions.props

The entire test execution is aborted on test failure because of broken serialization of the test failure report.
- Fix serialization of test reports to Godot variant type on EmitTestEvent.
- Add try catch block to report unexpected behaviors on test listener
- Fix error in statistics serialization, the key must be SnakeCase

GD-284: Fix test failure causes the entire test execution if it is executed in the Godot Editor

---

.github/workflows/ci-pr-publish-report.yml
.github/workflows/ci-pr.yml
Api.Test/src/asserts/CSharpTypes/AssertObjectTest.cs
Api.Test/src/asserts/GodotTypes/AssertObjectTest.cs
Api.Test/src/core/execution/TestEventTest.cs
Api/src/core/extensions/GodotObjectExtensions.cs

When a object has implemented the interfaces `IEquatable` or `IEqualityComparer` the deep comparison must use the specific provided equals implementation.
- Improved the deep comparison of objects by scan for these interfaces and use the provided implementation to compare objects.
- Add test coverage to verify the equal implementaions are called.

GD-318: Fixing object deep equal comparison (part2)

---

Api.Test/src/core/SceneRunnerInputEventIntegrationTest.cs
Api.Test/src/core/resources/scenes/TestSceneCSharp.tscn
Api/ReleaseNotes.txt
Api/src/core/SceneRunner.cs
ProjectVersions.props

The `SimulateKey ` produces an `InputEventKey` without setting the Unicode value. This will result in possible issues on text input components that act on Unicode values.
- Set the missing `Unicode` on  `InputEventKey` creation
- Add test coverage to simulate an text input

GD-331: Fixing SceneRunner `SimulateKey` to provide missing Unicode

---

Api/ReleaseNotes.txt
Api/src/core/discovery/TestCaseDiscoverer.cs
Example/ExampleProject.csproj
ProjectVersions.props

The script test discovery was broken on linux bash when having camel case names in the path.
- Do compare the script and navData path ignoring camel case.

GD-340: Fixing GdUnit4NetApiGodotBridge test discovery on linux paths

---

Api.Test/src/asserts/AssertEnumerableConditions.cs
Api.Test/src/asserts/CSharpTypes/AssertEnumerableTest.cs
Api.Test/src/asserts/GodotTypes/AssertEnumerableTest.cs
Api/src/core/extensions/GodotObjectExtensions.cs

When comparing an enumerable containing dictionaries, the comparison fails when the keys have a different order but it should succeeded.
- Adding check for dictionary type not compare it as enumerable
- Adding custom dictionary comparing to verify has same count and contains same keys and values

GD-343: Fix broken dictionary comparison at `GodotObjectExtensions `

---

Api.Test/src/core/TestSuiteTestAttributeUsage.cs
Api/ReleaseNotes.txt
Api/src/core/attributes/TestCaseAttribute.cs

When running test cases with parameters, using a single null parameter, it throws an exception and all test execution stops.
`[TestCase(null)]`
- Test for single null value and convert to an argument list containing a single null value

GD-339: Allow single `NULL` value as TestCase argument

---

Api.Test/src/core/SceneRunnerCSharpSceneTest.cs
Api.Test/src/core/SceneRunnerGDScriptSceneTest.cs
Api/ReleaseNotes.txt
Api/src/api/GodotAwaiterExtension.cs
Api/src/core/SceneRunner.cs
Api/src/core/execution/ExecutionStage.cs
Api/src/core/execution/exceptions/ExecutionTimeoutException.cs
Api/src/core/execution/exceptions/TestFailedException.cs
Api/src/core/reporting/TestReport.cs
Api/src/core/signals/GodotSignalCollector.cs
Example/ExampleProject.csproj
ProjectVersions.props

When waiting for a method and specify a timeout, the original method task is not canceled when the timeout is reached. This will result the original task is still running, and the cancellation toke is not freed.
- Rework on `GodotMethodAwaitable` task creation
- Using a thread save map to store the task id and cancellation token to handle `WithTimeout` cancellation of the running task
- Removed redundant task recreation to have a stable task id for cancellation
- Fixing `ExecutionTimeoutException` creation using the correct stack trace
Bump to release candidate 1

GD-348: Fixing task handling using `AwaitMethod` with `WithTimeout`
